### ISSUE TITLE
Include scikit-image in requirements

### ISSUE THREAD

**Issue by Joeclinton1** [warmshao/WiLoR-mini#2]
Great project btw!

I tried to run WiLorHandPose3dEstimationPipeline and got an error that skimage wasn't installed which was easily fixed by doing pip install scikit-image, so this just needs to be added to the requirements.

Alternatively it might be better to reduce imports by implementing a simple gaussian filter yourself in numpy.

**Comment by warmshao** [comment]
> Great project btw!
> 
> I tried to install and got an error that skimage wasn't installed which was easily fixed by doing pip install scikit-image, so this just needs to be added to the requirements.
> 
> Alternatively it might be better to reduce imports by implementing a simple gaussian filter yourself in numpy.

thank you! I will fix it today

**Comment by Joeclinton1** [comment]
> > Great project btw!
> > I tried to install and got an error that skimage wasn't installed which was easily fixed by doing pip install scikit-image, so this just needs to be added to the requirements.
> > Alternatively it might be better to reduce imports by implementing a simple gaussian filter yourself in numpy.
> 
> thank you! I will fix it today

thanks!
