### ISSUE TITLE
can't download file

### ISSUE THREAD

**Issue by yiyiyaya1122** [warmshao/WiLoR-mini#3]
File "/home/miniconda3/envs/omhand/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by warmshao** [comment]
> File "/home/miniconda3/envs/omhand/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error raise LocalEntryNotFoundError( huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

Make sure you can download models from the HuggingFace, you may need to set up a proxy or similar network configurations

**Comment by yiyiyaya1122** [comment]
alright,I just put all files in the right place. 
it works now

**Comment by warmshao** [comment]
> alright,I just put all files in the right place. it works now

great!
